config/routes.rb
TwittwarApp::Application.routes.draw do  
  devise_for :users
  resources :feeds
  
  get "home/index"
 
  get "/index"   => 'home#index'
  get "/profile" => 'feeds#profile'
  
  

  devise_scope :user do
  
    authenticated :user do
      get '/users' => 'devise/registrations#edit'
      root 'feeds#index', as: :authenticated_root
    end

    unauthenticated do
      get '/users' => 'devise/registrations#new'
      root 'home#index', as: :unauthenticated_root
    end
  end
    

end

app/models/feed.rb
class Feed < ActiveRecord::Base

  mount_uploader :feed_image, ImageUploader

  validate :checking_feed_text
  validate :checking_for_date
  validate :checking_for_image_size
 
  private
 
  def checking_for_image_size
    if feed_image.size > 300.kilobytes
      errors[:base] = "L\'immagine non puo\' superare 300 Kb"
    end 
  end
	
  def checking_feed_text
    if !(feed_text.present?)  
      errors[:base] = "Non puoi pubblicare feed vuoti!"
    elsif feed_image.present? and (feed_text.size > 101 or (feed_text_english.present? and feed_text_english.size > 101))         
      errors[:base] = "I feeds con immagini non possono contenere piu\' di 101 caratteri!"
    
      if feed_text_english.size > 101
        errors[:base] = "La versione Inglese del feed contienete piu\' di 101 caratteri"
      end
    elsif (feed_text.size > 124 or (feed_text_english.present? and feed_text_english.size > 124))
      errors[:base] = "I feeds non possono contenere piu\' di 124 caratteri!"         
    end
  end 
	
  def checking_for_date
    if !(date.present?) 
      errors[:base] = "E\' necessario inserire una data di pubblicazione per il feed!"
    elsif date.utc <= DateTime.now.utc
      errors[:base] = "La data di pubblicazione non puo\' essere nel passato!"
    end
  end
  
end

app/controllers/feeds_controller.rb
require 'google/api_client'
require 'json'

class FeedsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_feed, only: [:show, :edit, :update, :destroy]
	
  # error message for feeds not belonging to a user
  def error_message 
    flash.now[:notice] = "Non sei il possessore di questo feed e non detieni i privilegi per alterarlo!" 			
    render "show"
  end
  #  end #
		
  # GET /feeds
  def index
    @feeds = Feed.all
    @feed = Feed.new
  end
  # index end #

  # GET /feeds
  def profile
    @feeds = Feed.all
    @feed = Feed.new
  end
  # profile end # 
  
  # GET /feeds/1
  def show
  end
  # show end #

  # GET /feeds/new
  def new
    @feed = Feed.new
  end
  # new end #

  # GET /feeds/1/edit
  def edit

    # Show CET/CEST time to the user starting from the UTC time in the Database
    # TODO: have a better solution (see create action)
    @feed.date = @feed.date + 2.hour 

    if @feed.user_id != current_user.id
      error_message 
    elsif @feed.has_been_published == true
      flash[:notice] = "Non puoi modificare feed gia\' pubblicati"
      render "show"
    end

  end 
  # edit end #

  # POST /feeds
  def create
    @feed = Feed.new(feed_params)
    @feed.user_id = current_user.id

    # Here comes a quick dirty ugly workaround. Remember that:

    # --- The server (both application and Database) uses and stores time in UTC (Universal Time)
    # --- Feed dates are going to be entered by the user in the form
    # --- S/he will enter the time values according to Italian timezone
    # --- Currently (summer 2014), Italian time follows CEST (Central European Summer Time)
    # --- CEST is 2 hours beyond UTC
    # --- Important: after summer, Italian time will follow CET (Central European Time)
    # --- CET is 1 hour beyond UTC
 
    # So, for now, the dirty ugly workaround relies on converting the user-input CEST value to UTC 
    # using a simple 2 hour subtraction from the DateTime object.
    # This will have be be modified with a 1 hour subtraction when daylight saving time changes
    # TODO: have a better solution

    @feed.date = @feed.date - 2.hour 	

    # Translate from the original Italian text to English via Google Translate APIs in production mode
    if Rails.env.production?
      feed_text_english = translate_feed(@feed.feed_text)
      @feed.feed_text_english = feed_text_english
    end
        
    respond_to do |format|
      if @feed.save
        if feed_text_english.present?
          flash[:notice] = 'Entrambe le versioni del feed sono state create con successo'
        else
          flash[:notice] = 'La versione Italiana del feed e\' stata creata con successo'
        end
        format.html { render action: 'edit' }
      else
        format.html { render action: 'new' }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end
  # create end #

  # PATCH/PUT /feeds/1
  def update
    if @feed.user_id == current_user.id
      respond_to do |format|

        if @feed.update(feed_params)

          # Convert the CET/CEST time (inserted by the user) in UTC time (expected by the Database)
    	    # TODO: have a better solution (see create action)
    	    @feed.date = @feed.date - 2.hour

          flash[:notice] = 'Il Feed e\' stato aggiornato con successo'
          format.html { redirect_to action: 'index' }
        else
          format.html { render action: 'edit' }
          format.json { render json: @feed.errors, status: :unprocessable_entity }
        end
      end
    else
      error_message
    end
  end	
  # update end #
 
  # DELETE /feeds/1
  def destroy
    if @feed.user_id == current_user.id
      @feed.destroy
      respond_to do |format|
        format.html { redirect_to feeds_url }
        format.json { head :no_content }
      end
    else
      error_message
    end
  end	
  # destroy end #

  private
    # Use Google Translate APIs to translate feed text from the original Italian to English
    def translate_feed(feed_text)
	    google_client = Google::APIClient.new(
		    :application_name => APP_CONFIG['google']['production']['application_name'],
		    :key => APP_CONFIG['google']['production']['key'],
		    :application_version => '1.0.0',
		    :authorization => nil
	    )

	    # Load client secrets from your client_secrets.json
	    # NOT needed for the Google Translate APIs
	    # client_secrets = Google::APIClient::ClientSecrets.load
		
  	  translate = google_client.discovered_api('translate', 'v2')
	    result = google_client.execute(
	      :api_method => translate.translations.list,
	      :parameters => {
	      'format' => 'text',
	      'source' => 'it',
	      'target' => 'en',
	      'q' => feed_text
	      }
	    )
      
	    parsed = JSON.parse(result.data.to_json)
      
	    # Example of data returned 
      # {"translations":[{"translatedText":"This is a pen"}]}'
      
      english_translation = parsed["translations"][0]["translatedText"]
        
      # TODO: return a warning if the translation is over 140 characters (or whatever limit we have)

	    return english_translation
	   
    end
    # translate_feed end #

    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end
    # set_feed end #

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:feed_text, :feed_text_english, :date, :feed_image)
    end
    # feed_params end #
  end

app/helpers/feeds_helper.rb
module FeedsHelper
  def feed_error_messages!
    return "" if @feed.errors.empty?

    messages = @feed.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: @feed.errors.count,
                      resource: @feed.class.model_name.human.downcase)

    html = <<-HTML
      <h2 align="center">#{sentence}</h2>
      <b><h4 align="center">#{messages}</h4></b>
    HTML

    html.html_safe
  end
end

app/views/feeds/_doubleForm.html.erb
<%= form_for(@feed) do |f| %>
     
<%= feed_error_messages! %>

<ul id="mainTextBoxContainer">

  <li>      
    <%= f.text_area :feed_text, :class => "textBox", :onkeyup => 'textCounter(this, "charCounterIta");', :placeholder => "Scrivi qui il testo del tuo feed ..." %>
  </li>
  <li> 
    <table width="100%" style="color: green; font-weight: normal">
    <tr>
      <td id="charCounterIta" align="left"></td>
      <td id="charCounterEng" align="right"></td>
    </tr>
    </table>
  </li>
  <li>      
      <%= f.text_area :feed_text_english, :class => "textBox", :onkeyup => 'textCounter(this, "charCounterEng");', :placeholder => "Scrivi qui la versione inglese del feed ..." %>
  </li>
  <li>
    Inserisci la data di pubblicazione:</br>
    <%= f.datetime_select :date, :minute_step => 15 %>
  </li>
  <li>
    Inserisci un'immagine:</br>
    <%= f.file_field :feed_image %>
  </li>
  <li>
    <input type="submit" value="Conferma" class="button"/>
  </li>
  
</ul>
  
<% end %>

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
     
<%= feed_error_messages! %>
      
<ul id="mainTextBoxContainer">

  <li>      
    <%= f.text_area :feed_text, :class => "textBox", :onkeyup => 'textCounter(this, "charCounterIta");', :onclick => 'show_hide();', :placeholder => "Scrivi qui il testo del tuo feed ..." %>
  </li>
  <li id="charCounterIta" style="text-align: right; color: green; font-weight: normal">
    124
  </li>
  
  <div id="dateTimeBox">
    <li>
      Inserisci la data di pubblicazione:</br>
      <%= f.datetime_select :date, :minute_step => 15 %>
    </li>
    <li>
      Inserisci un'immagine:</br>
      <%= f.file_field :feed_image %>
    </li>
    <li>
      <input type="submit" value="Conferma" class="button"/>
    </li>
  </div>
  
</ul>

<% end %>

app/views/feeds/edit.html.erb
    <title>Modifica feed</title>
  </head>
  
  <body>
    
    <table border="0" class="header">
      <tr>
        <th id="logo">
          <a href="<%= @current_host %>"><%= image_tag("logo.png") %></a>
        </th>
        <th id="spacer"><!--inserire la barra di ricerca--></th>
        <th id="buttons">
          <a href="<%= @current_host %>" id="activeButton" name="Hlink">Home</a>
          <a href="<%= @current_host %>/profile" name="Hlink">Profilo</a>
          <a href="<%= edit_user_registration_path %>" name="Hlink">Impostazioni</a>
          <%= link_to 'Esci', destroy_user_session_path, method: :delete %>
        </th>
      </tr>
    </table>
    
    <div class="container">  
    
      <div class="groundSheet">
        <div class="homeTitle">
          Modifica il tuo feed
        </div>
        
        <% if notice %>
          <p align="center"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p align="center"><%= alert %></p>
        <% end %>
      
        <% if @feed.feed_image.present? %>
          <div id="<%= @feed.id %>" onclick="Expand_Image(<%= @feed.id %>)" class="feedImage">
            <%= image_tag(@feed.feed_image_url) %>
          </div>
        <% end %>
                
        <%= render 'doubleForm' %>
        
        <div class="bubble">
  	      <%= link_to 'Mostra', @feed %> |
          <%= link_to 'Indietro', :back %>
        </div>
      </div>
    
    </div>
  </body>
  
</html>

app/views/feeds/index.html.erb
    
    <title>La Grande Guerra</title>
  </head>  

  <body>
  
  <table border="0" class="header">
    <tr>
      <th id="logo">
        <a href="<%= @current_host %>"><%= image_tag("logo.png") %></a>
      </th>
      <th id="spacer"><!--inserire la barra di ricerca--></th>
      <th id="buttons">
        <a href="<%= @current_host %>" id="activeButton" name="Hlink">Home</a>
        <a href="<%= @current_host %>/profile" name="Hlink">Profilo</a>
        <a href="<%= edit_user_registration_path %>" name="Hlink">Impostazioni</a>
        <%= link_to 'Esci', destroy_user_session_path, method: :delete %>
      </th>
    </tr>
  </table>
  
  <div class="container">
  
    <div class="groundSheet">
          
      <div class="homeTitle">
        La Grande Guerra
      </div>
      
        <% if notice %>
          <p align="center"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p align="center"><%= alert %></p>
        <% end %>
         
        <%= render 'form' %>
    </div>
        
    <% if !@feeds.present? %>
    <div class="groundSheet">
      <div class="homeTitle"> 
        Benvenuto
      </div>
      
      <div class="homeTextRx">
          <p align="center">
            Tutti i vizi di tutte le età e di tutti i paesi del globo riuniti assieme<br> 
            non eguaglieranno mai i peccati che provoca<br>una sola campagna di guerra.
          </P>
          <h1 align="right">cit Voltaire</h1>
      </div>
    </div>
    <% else %>
      <% @feeds.reverse_each do |feed| %>
      <% read_usr = User.find(feed.user_id) %>

      <div class="groundSheet">
                       
        <% if read_usr.profile_image.present? %>
          <div class="imageBox">
            <%= image_tag(read_usr.profile_image_url) %>
          </div>
        <% end %>     
        
        <div class="postHead">
          <%= read_usr.user_name %>
        </div>
                     
        <div class="postDate">
          <% if feed.has_been_published == true %>
            Pubblicato in data: <%= feed.date.in_time_zone("CET").strftime('%d/%m/%Y %H:%M') %>
          <% else %>
            Da pubblicare in data: <%= feed.date.in_time_zone("CET").strftime('%d/%m/%Y %H:%M') %>
          <% end %>
        </div>
                             
        <% if feed.feed_image.present? %>
          <div id="<%= feed.id %>" onclick="Expand_Image(<%= feed.id %>)" class="feedImage">
            <%= image_tag(feed.feed_image_url) %>
          </div>
        <% end %>

        <div class="postText">
          <%= feed.feed_text %>
        </div>
        
        <% if feed.feed_text_english.present? %>
          <div class="engPostText">
            <%= feed.feed_text_english %>
          </div>
        <% end %>
                           
        <div class="bubble">
          <%= link_to 'Mostra', feed %>
        
          <% if feed.user_id == current_user.id and feed.has_been_published == false %>
            | <%= link_to 'Modifica', edit_feed_path(feed) %> |
            <%= link_to 'Elimina', feed, method: :delete, data: { confirm: 'Sei sicuro?' } %>
         <% end %>
        </div>
                  
      </div>
      <% end %>
    <% end %>
    
    </div>
  </body>
        
</html>

app/views/feeds/new.html.erb
    <title>Nuovo Feed</title>
  </head>
  
  <body>
    
    <table border="0" class="header">
      <tr>
        <th id="logo">
          <a href="<%= @current_host %>"><%= image_tag("logo.png") %></a>
        </th>
        <th id="spacer"><!--inserire la barra di ricerca--></th>
        <th id="buttons">
          <a href="<%= @current_host %>" id="activeButton" name="Hlink">Home</a>
          <a href="<%= @current_host %>/profile" name="Hlink">Profilo</a>
          <a href="<%= edit_user_registration_path %>" name="Hlink">Impostazioni</a>
          <%= link_to 'Esci', destroy_user_session_path, method: :delete %>
        </th>
      </tr>
    </table>
    	
    <div class="container">
      
      <div class="groundSheet">
        <div class="homeTitle">
          Nuovo feed
        </div>
      
        <% if notice %>
          <p align="center"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p align="center"><%= alert %></p>
        <% end %>
         
        <%= render 'form' %>
      
        <div class="bubble">
          <%= link_to 'Indietro', :back %>
        </div>
      </div>
    
    </div>
	</body>

</html>

app/views/feeds/profile.html.erb
    <title>Profilo</title>  
  </head>
    
  <body>
    
    <table border="0" class="header">
      <tr>
        <th id="logo">
          <a href="<%= @current_host %>"><%= image_tag("logo.png") %></a>
        </th>
        <th id="spacer"><!--inserire la barra di ricerca--></th>
        <th id="buttons">
          <a href="<%= @current_host %>" name="Hlink">Home</a>
          <a href="<%= @current_host %>/profile" id="activeButton" name="Hlink">Profilo</a>
          <a href="<%= edit_user_registration_path %>" name="Hlink">Impostazioni</a>
          <%= link_to 'Esci', destroy_user_session_path, method: :delete %>
        </th>
      </tr>
    </table>
    
    <div class="container">
    
      <div class="groundSheet">
        <div class="homeTitle">
          Ciao <%= current_user.user_name %>!
        </div>
      
          <% if notice %>
            <p align="center"><%= notice %></p>
          <% end %>
          <% if alert %>
            <p align="center"><%= alert %></p>
          <% end %>
        
        <%= render 'form' %>
      </div> 
  
      <% control_feed=0 %>
      <% @feeds.reverse_each do |feed| %>
        
        <% if feed.user_id == current_user.id %> 
          <% control_feed=1 %>

          <div class="groundSheet">
            
            <div class="postHead">
              <%= current_user.user_name %>
            </div>
                
            <div class="postDate">
              <% if feed.has_been_published == true %>
                Pubblicato in data: <%= feed.date.in_time_zone("CET").strftime('%d/%m/%Y %H:%M') %>
              <% else %>
                Da pubblicare in data: <%= feed.date.in_time_zone("CET").strftime('%d/%m/%Y %H:%M') %>
              <% end %>
            </div>
                
            <% if feed.feed_image.present? %>
              <div id="<%= feed.id %>" onclick="Expand_Image(<%= feed.id %>)" class="feedImage">
                <%= image_tag(feed.feed_image_url) %>
              </div>
            <% end %>

            <div class="postText">
              <%= feed.feed_text %>
            </div>
            
            <% if feed.feed_text_english.present? %>
              <div class="engPostText">
                <%= feed.feed_text_english %>
              </div>
            <% end %>
           
            <div class="bubble">
              <%= link_to 'Mostra', feed %>
              <% if feed.has_been_published == false %>
                | <%= link_to 'Modifica', edit_feed_path(feed) %> |
                <%= link_to 'Elimina', feed, method: :delete, data: { confirm: 'Sei sicuro?' } %>
              <% end %>
            </div>
            
        </div>

        <% end %>
      <% end %>
  
      <% if control_feed==0 %>
      <div class="groundSheet">
        <div class="homeTitle" align="center">
          Benvenuto nel tuo profilo!
        </div>
        
        <div class="homeTextRx">  
          <p align="center">
            Tutti gli uomini in fondo desiderano la guerra.<br><br>Essa porta con sé una semplificazione di tutto,<br> 
            che gli uomini sentono come sollievo.<br><br>Tutti trovano che la vita è troppo complicata.
          </p>
          <h1 align="right">cit Pär Lagerkvist</h1>
        </div>
      </div>
      <% end %> 
    
    </div>
  </body>
  
</html>

app/views/feeds/show.html.erb
    <title>Visualizza Feed</title>
  </head>
  
  <body>
  
    <table border="0" class="header">
      <tr>
        <th id="logo">
          <a href="<%= @current_host %>"><%= image_tag("logo.png") %></a>
        </th>
        <th id="spacer"><!--inserire la barra di ricerca--></th>
        <th id="buttons">
          <a href="<%= @current_host %>" id="activeButton" name="Hlink">Home</a>
          <a href="<%= @current_host %>/profile" name="Hlink">Profilo</a>
          <a href="<%= edit_user_registration_path %>" name="Hlink">Impostazioni</a>
          <%= link_to 'Esci', destroy_user_session_path, method: :delete %>
        </th>
      </tr>
    </table>
    
    <div class="container">
      
      <div class="groundSheet">
        <div class="homeTitle">
          Visualizza Feed:
        </div>
      
        <% if notice %>
          <p align="center"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p align="center"><%= alert %></p>
        <% end %>
      </div>
		
      <div class="groundSheet">
        <% read_usr = User.find(@feed.user_id) %>
      
        <% if read_usr.profile_image.present? %>
          <div class="imageBox">
            <%= image_tag(read_usr.profile_image_url, :width => 75 , :height => 75) %>
          </div>
        <% end %>

        <div class="postHead">
          <%= read_usr.user_name %>
        </div>
                
        <div class="postDate">
          <% if @feed.has_been_published == true %>
            Pubblicato in data: <%= @feed.date.in_time_zone("CET").strftime('%d/%m/%Y %H:%M') %>
          <% else %>
            Da pubblicare in data: <%= @feed.date.in_time_zone("CET").strftime('%d/%m/%Y %H:%M') %>
          <% end %>
        </div>
                
        <% if @feed.feed_image.present? %>
          <div id="<%= @feed.id %>" onclick="Expand_Image(<%= @feed.id %>)" class="feedImage">
            <%= image_tag(@feed.feed_image_url) %>
          </div>
        <% end %>

        <div class="postText">
          <%= @feed.feed_text %>
        </div>
        
        <% if @feed.feed_text_english.present? %>
          <div class="engPostText">
            <%= @feed.feed_text_english %>
          </div>
        <% end %>
        
        <div class="bubble">
          <% if @feed.user_id == current_user.id and @feed.has_been_published == false %>
            <%= link_to 'Modifica', edit_feed_path(@feed) %> |
          <% end %>       
        
          <%= link_to 'Indietro', :back %>
        </div>
      </div>
    
    </div>
  </body>
  
</html>